# NFL Analytics Configuration
# Copy this file to config/secrets.yaml and fill in your actual credentials

# ESPN API Configuration
espn:
  league_id: 537814  # Your league ID from the existing draft wizard
  year: 2025
  swid: "3C010FF1-0860-485F-BF82-17FC9D702287"  # Replace with your SWID from ESPN cookies
  espn_s2: "AECcLkXSS9TWmoGCbPewGJZMFuTRHRMfGyo7XiT2ssZGiJQGBeOxJGPK5HaqUvwu4jN%2F7kTGka1bbIdFv2FJhs0z%2FAimQ3Vg3w2GY49Ogr7V7JpB6r57B8Yx28oSFPnCk0Xi1EZUW2dlIFG%2FWbjNSplXUOjjFn%2F3pmpACqetH3g1zOe4YchwxSYNg2%2B2CPiyLshnpgm2wZ1PRRFkddMF8%2Fuu%2FowBXjAYWctsI1SUyrCVu%2BJQgpDvQtmlAkRZwCfp26rHz96YQwOtVvrsnM1MJMG8Z5LYZDu9WAnRcP9PgTuUhsTuYl81GcWvxH99tTXx0Dk%3D"  # Replace with your espn_s2 from ESPN cookies

# Database Configuration
database:
  path: "data/nfl_analytics.duckdb"
  backup_path: "data/backups/"
  
# Data Sources
data_sources:
  nfl_data_py:
    enabled: true
    years: [2023, 2024, 2025]
    
# Application Settings
app:
  log_level: "INFO"
  log_file: "logs/nfl_analytics.log"
  cache_ttl: 3600  # Cache timeout in seconds
  
# League Settings
league:
  scoring_type: "PPR"  # PPR, HALF_PPR, or STANDARD
  roster_positions:
    QB: 1
    RB: 2
    WR: 2
    TE: 1
    FLEX: 2
    OP: 1  # Superflex
    K: 1
    DST: 1
    BENCH: 7
    
# Analytics Settings
analytics:
  stability_windows: [3, 5, 8]  # Weeks for stability calculations
  projection_method: "weighted"  # simple, weighted, or advanced
  confidence_threshold: 0.7
  
# CLI Settings
cli:
  output_format: "table"  # table, json, or csv
  color_output: true
  page_size: 10